// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LidarMsg.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_LIDARMSG_H_
#define _FAST_DDS_GENERATED_LIDARMSG_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(LidarMsg_SOURCE)
#define LidarMsg_DllAPI __declspec( dllexport )
#else
#define LidarMsg_DllAPI __declspec( dllimport )
#endif // LidarMsg_SOURCE
#else
#define LidarMsg_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define LidarMsg_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure LidarMessage defined by the user in the IDL file.
 * @ingroup LIDARMSG
 */
class LidarMessage
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport LidarMessage();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~LidarMessage();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object LidarMessage that will be copied.
     */
    eProsima_user_DllExport LidarMessage(
            const LidarMessage& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object LidarMessage that will be copied.
     */
    eProsima_user_DllExport LidarMessage(
            LidarMessage&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object LidarMessage that will be copied.
     */
    eProsima_user_DllExport LidarMessage& operator =(
            const LidarMessage& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object LidarMessage that will be copied.
     */
    eProsima_user_DllExport LidarMessage& operator =(
            LidarMessage&& x);

    /*!
     * @brief Comparison operator.
     * @param x LidarMessage object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const LidarMessage& x) const;

    /*!
     * @brief Comparison operator.
     * @param x LidarMessage object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const LidarMessage& x) const;

    /*!
     * @brief This function sets a value in member scan_time
     * @param _scan_time New value for member scan_time
     */
    eProsima_user_DllExport void scan_time(
            float _scan_time);

    /*!
     * @brief This function returns the value of member scan_time
     * @return Value of member scan_time
     */
    eProsima_user_DllExport float scan_time() const;

    /*!
     * @brief This function returns a reference to member scan_time
     * @return Reference to member scan_time
     */
    eProsima_user_DllExport float& scan_time();

    /*!
     * @brief This function copies the value in member ranges
     * @param _ranges New value to be copied in member ranges
     */
    eProsima_user_DllExport void ranges(
            const std::array<float, 455>& _ranges);

    /*!
     * @brief This function moves the value in member ranges
     * @param _ranges New value to be moved in member ranges
     */
    eProsima_user_DllExport void ranges(
            std::array<float, 455>&& _ranges);

    /*!
     * @brief This function returns a constant reference to member ranges
     * @return Constant reference to member ranges
     */
    eProsima_user_DllExport const std::array<float, 455>& ranges() const;

    /*!
     * @brief This function returns a reference to member ranges
     * @return Reference to member ranges
     */
    eProsima_user_DllExport std::array<float, 455>& ranges();
    /*!
     * @brief This function copies the value in member intensities
     * @param _intensities New value to be copied in member intensities
     */
    eProsima_user_DllExport void intensities(
            const std::array<float, 455>& _intensities);

    /*!
     * @brief This function moves the value in member intensities
     * @param _intensities New value to be moved in member intensities
     */
    eProsima_user_DllExport void intensities(
            std::array<float, 455>&& _intensities);

    /*!
     * @brief This function returns a constant reference to member intensities
     * @return Constant reference to member intensities
     */
    eProsima_user_DllExport const std::array<float, 455>& intensities() const;

    /*!
     * @brief This function returns a reference to member intensities
     * @return Reference to member intensities
     */
    eProsima_user_DllExport std::array<float, 455>& intensities();

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const LidarMessage& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    float m_scan_time;
    std::array<float, 455> m_ranges;
    std::array<float, 455> m_intensities;
};

#endif // _FAST_DDS_GENERATED_LIDARMSG_H_