<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ldlidar_dds_server</name>
  <version>0.1.0</version>
  <description>DDS server package: read LDLiDAR and publish scan data over FastDDS.</description>

  <maintainer email="vungoctruong8x@gmail.com">tvn</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>ldlidar_component</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
