// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LidarMsg.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "LidarMsg.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

LidarMessage::LidarMessage()
{
    // m_scan_time com.eprosima.idl.parser.typecode.PrimitiveTypeCode@43bd930a
    m_scan_time = 0.0;
    // m_ranges com.eprosima.idl.parser.typecode.ArrayTypeCode@33723e30
    memset(&m_ranges, 0, (455) * 4);
    // m_intensities com.eprosima.idl.parser.typecode.ArrayTypeCode@64f6106c
    memset(&m_intensities, 0, (455) * 4);

}

LidarMessage::~LidarMessage()
{



}

LidarMessage::LidarMessage(
        const LidarMessage& x)
{
    m_scan_time = x.m_scan_time;
    m_ranges = x.m_ranges;
    m_intensities = x.m_intensities;
}

LidarMessage::LidarMessage(
        LidarMessage&& x)
{
    m_scan_time = x.m_scan_time;
    m_ranges = std::move(x.m_ranges);
    m_intensities = std::move(x.m_intensities);
}

LidarMessage& LidarMessage::operator =(
        const LidarMessage& x)
{

    m_scan_time = x.m_scan_time;
    m_ranges = x.m_ranges;
    m_intensities = x.m_intensities;

    return *this;
}

LidarMessage& LidarMessage::operator =(
        LidarMessage&& x)
{

    m_scan_time = x.m_scan_time;
    m_ranges = std::move(x.m_ranges);
    m_intensities = std::move(x.m_intensities);

    return *this;
}

bool LidarMessage::operator ==(
        const LidarMessage& x) const
{

    return (m_scan_time == x.m_scan_time && m_ranges == x.m_ranges && m_intensities == x.m_intensities);
}

bool LidarMessage::operator !=(
        const LidarMessage& x) const
{
    return !(*this == x);
}

size_t LidarMessage::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += ((455) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += ((455) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t LidarMessage::getCdrSerializedSize(
        const LidarMessage& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    if ((455) > 0)
    {
        current_alignment += ((455) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    }

    if ((455) > 0)
    {
        current_alignment += ((455) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    }


    return current_alignment - initial_alignment;
}

void LidarMessage::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_scan_time;
    scdr << m_ranges;

    scdr << m_intensities;


}

void LidarMessage::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_scan_time;
    dcdr >> m_ranges;

    dcdr >> m_intensities;

}

/*!
 * @brief This function sets a value in member scan_time
 * @param _scan_time New value for member scan_time
 */
void LidarMessage::scan_time(
        float _scan_time)
{
    m_scan_time = _scan_time;
}

/*!
 * @brief This function returns the value of member scan_time
 * @return Value of member scan_time
 */
float LidarMessage::scan_time() const
{
    return m_scan_time;
}

/*!
 * @brief This function returns a reference to member scan_time
 * @return Reference to member scan_time
 */
float& LidarMessage::scan_time()
{
    return m_scan_time;
}

/*!
 * @brief This function copies the value in member ranges
 * @param _ranges New value to be copied in member ranges
 */
void LidarMessage::ranges(
        const std::array<float, 455>& _ranges)
{
    m_ranges = _ranges;
}

/*!
 * @brief This function moves the value in member ranges
 * @param _ranges New value to be moved in member ranges
 */
void LidarMessage::ranges(
        std::array<float, 455>&& _ranges)
{
    m_ranges = std::move(_ranges);
}

/*!
 * @brief This function returns a constant reference to member ranges
 * @return Constant reference to member ranges
 */
const std::array<float, 455>& LidarMessage::ranges() const
{
    return m_ranges;
}

/*!
 * @brief This function returns a reference to member ranges
 * @return Reference to member ranges
 */
std::array<float, 455>& LidarMessage::ranges()
{
    return m_ranges;
}
/*!
 * @brief This function copies the value in member intensities
 * @param _intensities New value to be copied in member intensities
 */
void LidarMessage::intensities(
        const std::array<float, 455>& _intensities)
{
    m_intensities = _intensities;
}

/*!
 * @brief This function moves the value in member intensities
 * @param _intensities New value to be moved in member intensities
 */
void LidarMessage::intensities(
        std::array<float, 455>&& _intensities)
{
    m_intensities = std::move(_intensities);
}

/*!
 * @brief This function returns a constant reference to member intensities
 * @return Constant reference to member intensities
 */
const std::array<float, 455>& LidarMessage::intensities() const
{
    return m_intensities;
}

/*!
 * @brief This function returns a reference to member intensities
 * @return Reference to member intensities
 */
std::array<float, 455>& LidarMessage::intensities()
{
    return m_intensities;
}

size_t LidarMessage::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;






    return current_align;
}

bool LidarMessage::isKeyDefined()
{
    return false;
}

void LidarMessage::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
       
}
